# Generated by Django 6.0.6 on 2026-06-12 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
